# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: '3'
vars:
  TESTING_DIR: './backend/Testing'
  HG_REPO_DIR: './hgweb/repos'
includes:
  k8s:
    taskfile: ./deployment/Taskfile.yml
    dir: ./deployment
  gh:
    dir: .
    taskfile: ./.github/Taskfile.yml
  ui:
    taskfile: ./frontend/Taskfile.yml
    dir: ./frontend
  api:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend

tasks:
  setup:
    deps: [ setup-win, setup-unix ]
    cmds:
      - git config blame.ignoreRevsFile .git-blame-ignore-revs
      - echo HONEYCOMB_API_KEY=__REPLACE__ >> deployment/dev/local.env
  setup-win:
    platforms: [ windows ]
    cmds:
      - cmd: powershell rm -r {{.HG_REPO_DIR}}/sena-3
        ignore_error: true
        silent: true
      - powershell -Command "Invoke-WebRequest 'https://drive.google.com/uc?export=download&id=1I-hwc0RHoQqW774gbS5qR-GHa1E7BlsS' -OutFile sena-3.zip"
      - powershell -Command "Expand-Archive sena-3.zip -DestinationPath {{.HG_REPO_DIR}}"
      - powershell rm sena-3.zip
  setup-unix:
    platforms: [ linux, darwin ]
    cmds:
      - cmd: rm -rf {{.HG_REPO_DIR}}/sena-3
        ignore_error: true
        silent: true
      - wget -O sena-3.zip 'https://drive.google.com/uc?export=download&id=1I-hwc0RHoQqW774gbS5qR-GHa1E7BlsS'
      - unzip -q sena-3.zip -d {{.HG_REPO_DIR}}/
      - rm sena-3.zip

  # k8s
  up:
    cmds:
      - skaffold dev --cleanup=false --kube-context docker-desktop

  # tests
  test:
    dir: '{{.TESTING_DIR}}'
    cmds:
      - dotnet test --filter=Category!=Integration
  test-sr:
    dir: '{{.TESTING_DIR}}'
    deps: [ up ]
    cmds:
      - dotnet test --filter=SendReceive
  test-integration:
    dir: '{{.TESTING_DIR}}'
    deps: [ up ]
    cmds:
      - dotnet test --filter Category=Integration
  test-integration-staging:
    cmds:
      - dotnet test --filter Category=Integration  -s ./backend/Testing/staging.runsettings.xml

      # dev
  infra-up:
    desc: Starts infrastructure for our ui and api
    cmds:
      - skaffold run --cleanup=false --kube-context docker-desktop --profile=infra

  dev: # Currently broken (because the ui doesn't wait for the api), but probably no one uses it.
    deps: [ api-dev, ui:ui-only]
    interactive: true

  ui-dev:
    aliases: [ ui ]
    desc: The single command for local ui development
    dir: ./frontend
    deps: [ infra-up ]
    interactive: true
    cmds:
      - task: ui:only

      # api
  api-dev:
    aliases: [ api ]
    desc: The single command for local api development
    deps: [ infra-up ]
    interactive: true
    cmds:
      - task: api:only


