apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: languagedepot

configMapGenerator:
  - name: otel-config
    files:
      - collector-config.yaml
  - name: hg-config
    files:
      - hg.conf
      - hgweb.hgrc

resources:
- pvc.yaml
- db-deployment.yaml
- hg-deployment.yaml
- lexbox-deployment.yaml
- ui-deployment.yaml
- proxy-deployment.yaml
