apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: languagedepot

configMapGenerator:
  - name: hg-config
    options:
      disableNameSuffixHash: true
    files:
      - hg.conf
      - hgweb.hgrc

