  name: dotnet integration
  description: run's dotnet integration tests in a docker container for environment consistency
  inputs:
    hostname:
      description: "Target host to run the integration tests against"
      required: true
    project-code:
      description: "Project code to run S&R tests against"
      required: false
      default: 'sena-3'
    password:
        description: "Password to use for the test user"
        required: true
  runs:
    using: docker
    image: 'action.Dockerfile'
    args:
      - sh
      - ./.github/actions/dotnet-integration/run-tests.sh
    env:
      TEST_SERVER_HOSTNAME: ${{ inputs.hostname }}
#      this is not a typo, we need to use the lf domain because it has a cert that hg will validate
      TEST_STANDARD_HG_HOSTNAME: hg-staging.languageforge.org
      TEST_RESUMABLE_HG_HOSTNAME: resumable-${{ inputs.hostname }}
      TEST_PROJECT_CODE: ${{ inputs.project-code }}
      TEST_DEFAULT_PASSWORD: ${{ inputs.password }}
