apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: languagedepot

configMapGenerator:
  - name: otel-config
    options:
      disableNameSuffixHash: true
    files:
      - collector-config.yaml
