name: integration action testing
on:
  push:
    branches:
      - integration-action-testing
  workflow_call:
  workflow_dispatch:
    inputs:
      project-code:
          description: "Project code to run S&R tests against"
          required: false
          default: 'sena-3'

#todo deduplicate this code from the code in lexbox-api.yaml
jobs:
  test-integration-tests:
    runs-on: ${{ matrix.os }}
    environment:
      name: staging
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7'
      - uses: MatteoH2O1999/setup-python@v1.5.0
        id: python
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          python-version: '2.7.18'
          cache-build: true
          allow-build: allow
      - name: Link python
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo ln -s ${{ steps.python.outputs.python-path }} /usr/bin/python2
      - name: Dotnet build
        run: dotnet build
      - name: Playwright setup
        run: pwsh backend/Testing/bin/Debug/net7.0/playwright.ps1 install
      - name: Integration tests
        env:
          TEST_SERVER_HOSTNAME: staging.languagedepot.org
            #      this is not a typo, we need to use the lf domain because it has a cert that hg will validate
          TEST_STANDARD_HG_HOSTNAME: hg-staging.languageforge.org
          TEST_RESUMABLE_HG_HOSTNAME: resumable-staging.languagedepot.org
          TEST_PROJECT_CODE: 'sena-3'
          TEST_DEFAULT_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        run: dotnet test --logger trx --results-directory ./testresults --filter "VerifyHgWorking|CloneBigProject"
      - name: Upload test results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always() && !env.act
        with:
          check_name: Manual Integration Tests ${{ matrix.os }}
          files: ./testresults/*.trx
