on:
  workflow_call:
  workflow_dispatch:
    inputs:
      project-code:
          description: "Project code to run S&R tests against"
          required: false
          default: 'sena-3'

jobs:
  test-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dotnet-integration
        with:
          hostname: staging.languagedepot.org
          project-code: ${{ inputs.project-code }}
