name: hgweb

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    paths:
      - 'hgweb/**'
      - '.github/workflows/lexbox-hgweb.yaml'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'hgweb/**'
      - '.github/workflows/lexbox-hgweb.yaml'
    branches:
      - main
      - develop

env:
  PROD_RELEASE: ${{github.ref == vars.PROD_BRANCH}}
  IMAGE_NAME: ghcr.io/sillsdev/lexbox-hgweb

jobs:
  publish-hgweb:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setVersion.outputs.VERSION }}

    env:
      # https://docs.docker.com/develop/develop-images/build_enhancements/
      DOCKER_BUILDKIT: 1

    steps:
      -
        uses: actions/checkout@v3
      - name: Set Version
        id: setVersion
        # set version to date in vYYYY-MM-DD format
        run: |
          echo "VERSION=v$(date --rfc-3339=date)" >> ${GITHUB_ENV}
          echo "VERSION=v$(date --rfc-3339=date)" >> ${GITHUB_OUTPUT}

      - name: Docker meta
        id: meta
        if: ${{ !env.ACT }}
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,enable=${{ env.PROD_RELEASE }},value=latest
            type=raw,enable=${{ env.PROD_RELEASE }},value=${{ env.VERSION }}
      -
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: docker/build-push-action@v4
        with:
          context: hgweb
          build-args: |
            APP_VERSION=${{ env.VERSION }}
          push: ${{ !env.ACT }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy-hgweb:
      uses: ./.github/workflows/deploy.yaml
      if: ${{github.ref == vars.PROD_BRANCH}}
      secrets: inherit
      needs: publish-hgweb
      with:
        version: ${{ needs.publish-hgweb.outputs.version }}
        image: 'ghcr.io/sillsdev/lexbox-hgweb'
